---
scheme: http
proxyPort: 80

# Needs to be filled
openprojectApi:
  username:
  password:
  apikey:

apps:
  openproject:
    hostname: track.local.bcc3d.ca
  bcc3d_ca:
    hostname: www.local.bcc3d.ca
